$color = rgba(41, 43, 49, 1)
$inner_color = rgba(41, 43, 49, 0.66)
$outer_color = rgba(209, 86, 70, 1)
$font_color = rgba(214, 209, 201, 1)
$placeholder_color = rgba(214, 209, 201, 0.7)
$check_color = rgba(155, 144, 127, 1)
