background            #292b31
foreground            #d6d1c9

# black
color0  #292b31
color8  #b4ab99

# red
color1  #dd5544
color9  #f28b7c

# green
color2  #76856a
color10 #a8b49d

# yellow
color3  #f3e9bd
color11 #fff4d4

# blue
color4  #bda07f
color12 #d8c3a5

# magenta
color5  #b7a593
color13 #b0a89d

#cyan
color6  #9b907f
color14 #c7c0b5

#white
color7  #ffffff
color15 #d6d1c9


